[package]
name = "leptos_fluid_example"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos_fluid = { path = "../", features = ["view-transitions", "motion"] }
leptos = { version = "0.8", default-features = false, features = ["csr"] }
leptos_meta = { version = "0.8", default-features = false }
leptos_router = { version = "0.8", default-features = false }
console_error_panic_hook = { version = "0.1" }
