cargo-features = ["panic-immediate-abort"]

[workspace]
members = ["example", "example_motion", "crates/flip", "crates/view_transitions", "crates/motion"]

[package]
name = "leptos_fluid"
version = "0.1.1"
edition = "2024"

[dependencies]
leptos_fluid_flip = { path = "crates/flip", optional = true, package = "leptos_fluid_flip" }
leptos_fluid_view_transitions = {
    path = "crates/view_transitions",
    optional = true,
    package = "leptos_fluid_view_transitions",
}
leptos_fluid_motion = { path = "crates/motion", optional = true, package = "leptos_fluid_motion" }

[features]
default = []
flip = ["dep:leptos_fluid_flip"]
view-transitions = ["dep:leptos_fluid_view_transitions"]
motion = ["dep:leptos_fluid_motion"]
full = ["flip", "view-transitions", "motion"]
