mod color_morph;
mod counter;
mod footer;
mod horizontal_gallery;
mod image_reveal;
mod magnetic_cta;
mod perspective_tilt;
mod sticky_hero;
mod stagger_grid;
mod text_mask_reveal;
mod velocity_marquee;

pub use color_morph::ColorMorphSection;
pub use counter::CounterSection;
pub use footer::FooterSection;
pub use horizontal_gallery::HorizontalGallerySection;
pub use image_reveal::ImageRevealSection;
pub use magnetic_cta::MagneticCtaSection;
pub use perspective_tilt::PerspectiveTiltSection;
pub use sticky_hero::StickyHeroSection;
pub use stagger_grid::StaggerGridSection;
pub use text_mask_reveal::TextMaskRevealSection;
pub use velocity_marquee::VelocityMarqueeSection;