[package]
name = "leptos_fluid_motion_example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
leptos_fluid_motion = { path = "../crates/motion", default-features = false, features = ["spring", "controller", "timeline", "builders", "macros", "auto-size"] }
leptos_fluid_flip = { path = "../crates/flip" }
leptos = { workspace = true }
console_error_panic_hook = { workspace = true }
