[package]
name = "leptos_fluid_view_transitions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Nested outlet route transition primitives for leptos_router."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/leptos_fluid_view_transitions"
keywords = ["leptos", "router", "animation", "transitions", "wasm"]
categories = ["wasm", "web-programming", "gui"]

[dependencies]
leptos = { workspace = true }
leptos_router = { workspace = true }
web-sys = { workspace = true, features = [
    "AnimationEvent",
    "Element",
    "Navigator",
    "NodeList",
    "PopStateEvent",
    "Window",
] }
