[package]
name = "leptos_fluid_view_transitions"
version = "0.1.1"
edition = "2024"

[dependencies]
leptos = { version = "0.8.15", default-features = false, features = ["csr"] }
leptos_router = { version = "0.8.11", default-features = false }
web-sys = { version = "0.3.69", features = [
    "AnimationEvent",
    "Element",
    "Navigator",
    "Node",
    "NodeList",
    "PopStateEvent",
    "Window",
] }
