[package]
name = "leptos_fluid_flip"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "FLIP animations for Leptos layout transitions, movement, and reordering."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/leptos_fluid_flip"
keywords = ["leptos", "animation", "flip", "ui", "wasm"]
categories = ["wasm", "web-programming", "gui"]

[dependencies]
leptos = { workspace = true }
leptos_fluid_web = { version = "0.1.1", path = "../web", default-features = false, features = ["waapi", "dom-query"] }
web-sys = { workspace = true, features = [
    "DomRect",
    "Element",
    "Animation",
    "CssStyleDeclaration",
    "Window",
    "Document",
] }
