[package]
name = "leptos_fluid_flip"
version = "0.1.1"
edition = "2024"

[dependencies]
leptos = { version = "0.8.15", default-features = false, features = ["csr"] }
leptos_fluid_web = { path = "../web" }
web-sys = { version = "0.3.69", features = [
    "DomRect",
    "Element",
    "Animation",
    "CssStyleDeclaration",
    "Window",
    "Document",
] }
